Mysql:
  Host: 10.0.88.137
  Port: 3306
  Username: erinyes
  Password: Erinyes@2024
  DBName: erinyes_mine
  MaxOpenConns: 100
  MaxIdleConns: 10
Service:
  Port: ":8080"
IPMap:
  10.10.0.118: zjy-2n-product-purchase$7694d4878-rf9n2
  10.10.0.117: zjy-2n-product-purchase-authorize-cc$7d4ff45cc-c9vbj
  10.10.0.115: zjy-2n-product-purchase-get-price$d46b8f877-zvtlg
  10.10.0.116: zjy-2n-product-purchase-publish$74fc4fb89c-hk76b
GatewayMap:
  10.102.89.199: true
  10.103.118.113: true
HostIP: 10.0.88.125
Cin0IP: 10.10.0.1